BlockRemover:
  # 方块消失时间单位 秒
  Period: 10
  # 检查的时间间隔 单位tick
  CheckPeriod: 20
  #启用的世界
  Worlds:
    - world
    - world_nether
    - world_the_end
  #玩家白名单
  Players:
    - Iceaso

  #方块白名单,为 Material 枚举(部分)省略颜色
  Blocks:
    - SHULKER_BOX
    - CHEST
    - ENDER_CHEST






